
# Define colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (128, 128, 128)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
PURPLE = (128, 0, 128)
PINK = (250, 192, 225, 128)
YELLOW =  (255, 255, 0)

# Define constants
SCREEN_WIDTH=1200
SCREEN_HEIGHT=800
WIDTH = 800
HEIGHT = 800
BUTTON_SIZE=40



# Define Globals
FPS = 60
NUM_ROBOTS = 20
NUM_OBSTACLES = 0   #Original 5
NUM_TARGETS = 0     #Original 3
ROBOT_SIZE = 5
OBSTACLE_RADIUS = 50
Target_RADIUS = 30
MISSION_BASE_RADIUS = 10
SCALE_CURRENT = 1 
MAX_PHEROMONE_INTENSITY=600
MAX_PHEROMONE_RADIUS=120
SPREAD_SPEED=MAX_PHEROMONE_RADIUS/MAX_PHEROMONE_INTENSITY
GRID_WIDTH=800
GRID_HEIGHT=800
WIDTH_SCALE=WIDTH/GRID_WIDTH
HEIGHT_SCALE=HEIGHT/GRID_HEIGHT

# Robot Attributes
MAX_SPEED = 3
MAX_ACCELERATION = 0.9
SENSOR_RADIUS = 30 #Original Value 10


# don't mess with this
def scale_map(SCALE):
    global SCALE_CURRENT; global MAX_SPEED; global MAX_ACCELERATION; global SENSOR_RADIUS
    global ROBOT_SIZE; global OBSTACLE_RADIUS; global Target_RADIUS
   
    MAX_SPEED = SCALE_CURRENT * MAX_SPEED / SCALE
    MAX_ACCELERATION = SCALE_CURRENT * MAX_ACCELERATION / SCALE
    SENSOR_RADIUS = SCALE_CURRENT * SENSOR_RADIUS / SCALE
    ROBOT_SIZE = SCALE_CURRENT * ROBOT_SIZE / SCALE
    OBSTACLE_RADIUS = SCALE_CURRENT * OBSTACLE_RADIUS / SCALE
    Target_RADIUS = SCALE_CURRENT * Target_RADIUS / SCALE
    SCALE_CURRENT = SCALE
# don't mess with this
scale_map(1)


